# Override default controlplane image location

## NEWSITE_CHANGED: update the file with the ephemeral node pxe ip
apiVersion: airshipit.org/v1alpha1
kind: VersionsCatalogue
metadata:
  name: versions-airshipctl

spec:
  files:
    k8scontrol:
      # Host the image in a locally served location for CI
      # NEWSITE_CHANGED: update the url with the ephemeral node pxe ip
      cluster_controlplane_image:
        url: http://172.63.0.14/images/control-plane.qcow2
        checksum: http://172.63.0.14/images/control-plane.qcow2.md5sum
