apiVersion: airshipit.org/v1alpha1
kind: BaremetalManager
metadata:
  name: RemoteDirectEphemeral
spec:
  hostSelector:
    ## NEWSITE_CHANGED: ephemeral node
    name: bm132
  operationOptions:
    remoteDirect:
      ## NEWSITE_CHANGED: URL to the ephemeral node iso 
      isoURL: http://172.63.0.1/ephemeral.iso
