# This makes a couple small networking tweaks that are specific to the
# ephemeral cluster, on top of the target cluster networking definition.
# These values can be overridden at the site, type, etc levels as appropriate.

## NEWSITE_CHANGED: update file with ephemeral node ips
apiVersion: airshipit.org/v1alpha1
kind: NetworkCatalogue
metadata:
  name: networking
spec:
  kubernetes:
    serviceCidr: "10.96.0.0/12"
    podCidr: "192.168.0.0/18"
    controlPlaneEndpoint:
      # NEWSITE_CHANGED: Ephemeral node oam ip
      host: "10.254.125.229"
      port: 6443
    # NEWSITE_CHANGED: ephemeral node calico ip and pxe ip
    apiserverCertSANs: "[172.64.0.32, 172.63.0.14]"
  ironic:
    # NEWSITE_CHANGED: Ephemeral node PXE network
    provisioningInterface: "eno3"
    provisioningIp: "172.63.0.14"
    dhcpRange: "172.63.0.31,172.63.0.126"
